import type { AnatomicalRole } from './types';

export const ROLES: AnatomicalRole[] = [
  'Cranium',
  'Mandible',
  'Cervical',
  'Thoracic',
  'Lumbar',
  'Pelvis',
  'Sacrum',
  'Humerus_L',
  'Humerus_R',
  'Radius_L',
  'Radius_R',
  'Carpal_L',
  'Carpal_R',
  'Femur_L',
  'Femur_R',
  'Tibia_L',
  'Tibia_R',
  'Tarsal_L',
  'Tarsal_R',
  'Caudal_Seg',
  'Dorsal_Ext',
  'Aileron',
  'Prop_Weapon',
  'Prop_Misc',
  'Custom',
];

export const AUTO_PARENTS: Partial<Record<AnatomicalRole, AnatomicalRole>> = {
  Cranium: 'Cervical',
  Mandible: 'Cranium',
  Cervical: 'Thoracic',
  Thoracic: 'Lumbar',
  Lumbar: 'Pelvis',
  Sacrum: 'Pelvis',
  Humerus_L: 'Thoracic',
  Radius_L: 'Humerus_L',
  Carpal_L: 'Radius_L',
  Humerus_R: 'Thoracic',
  Radius_R: 'Humerus_R',
  Carpal_R: 'Radius_R',
  Femur_L: 'Pelvis',
  Tibia_L: 'Femur_L',
  Tarsal_L: 'Tibia_L',
  Femur_R: 'Pelvis',
  Tibia_R: 'Femur_R',
  Tarsal_R: 'Tibia_R',
  Caudal_Seg: 'Sacrum',
  Dorsal_Ext: 'Thoracic',
  Aileron: 'Thoracic',
};

export const ROLE_COLORS: Record<string, string> = {
  Cranium: '#e87a5d',
  Mandible: '#e8a05d',
  Cervical: '#d4a017',
  Thoracic: '#4a9e4a',
  Lumbar: '#3d8f8f',
  Pelvis: '#7b5ea7',
  Sacrum: '#5e7ab5',
  Humerus_L: '#c07070',
  Humerus_R: '#c07070',
  Radius_L: '#b06060',
  Radius_R: '#b06060',
  Carpal_L: '#a05050',
  Carpal_R: '#a05050',
  Femur_L: '#7070c0',
  Femur_R: '#7070c0',
  Tibia_L: '#6060b0',
  Tibia_R: '#6060b0',
  Tarsal_L: '#5050a0',
  Tarsal_R: '#5050a0',
  Caudal_Seg: '#8a7a4a',
  Dorsal_Ext: '#4a8a7a',
  Aileron: '#7a4a8a',
  Custom: '#9b59b6',
};

export const MODE_NAMES: Record<string, string> = {
  harvest: 'Harvest',
  rig: 'Rig',
  pose: 'Pose',
  cut: 'Cut',
  merge: 'Merge',
};

